### ISSUE TITLE
Feature request: make it configurable which items to stack, and configurable stacksize

### ISSUE THREAD

**Issue by Zevac-ZSF** [bakrun/stackitem64#1]
Hello, nice mod :-)

Can you make it possible to configure which items to stack and which not?

And to configure the max stack size per item?

Example, I would only like to stack lave, snow, water buckets to 16, nothing else

Thank you in advance :-)

Z.

**Comment by bakrun** [comment]
I will be try to that

**Comment by bakrun** [comment]
It is possible to configure which items to stack 

config/stackitem.json5 file use

**Comment by Zevac-ZSF** [comment]
I just tested it, it works great with the full buckets ! Thank you :-)

I did find something strange. Shulkerbox stacking is handled via Carpet mod (by Gnembon), it stacks on the ground, but not inside containers (ea hoppers, chests etc). But your code changed that. it now also stacks inside containers. Can you fix that?

Thank you again :-)

**Comment by bakrun** [comment]
maybe minecraft/config/stackitem.json5 modify delete shulkerbox, or shulkerbox stack to 1

**Comment by Zevac-ZSF** [comment]
I already tried that, same result shulkerboxes stack inside containers to 64:

{
  "ItemName": ["minecraft:water_bucket","minecraft:lava_bucket","minecraft:powder_snow_bucket","minecraft:milk_bucket"],
  "ItemStack": [16,16,16,16]
}

and 

{
  "ItemName": ["minecraft:water_bucket","minecraft:lava_bucket","minecraft:powder_snow_bucket","minecraft:milk_bucket","minecraft:shulker_box"],
  "ItemStack": [16,16,16,16,1]
}

**Comment by bakrun** [comment]
Is Carpet mod default stackableShulkerBoxes true? check carpet mod rules

**Comment by Zevac-ZSF** [comment]
Yes, I did not change anything in Carpet. so default stackableShulkerBoxes=true, as it has been for years now :-)

**Comment by Zevac-ZSF** [comment]
I've used several stackable mods over the years, and all worked fine with Carpet. I always only stacked filled buckets to 16, and left Carpet to deal with the Shulkerboxes. Last one I used was Stackables by Roundaround (for MC 1.20.1), but sadly he's not updating soon. Maybe you can compare code?

**Comment by bakrun** [comment]
this issue isnew vanilla feature in 1.20.5+  [this](https://github.com/gnembon/fabric-carpet/issues/1934)

if return shulkerbox behavior use  [this mod](https://modrinth.com/mod/stackable-shulkers-fix)

**Comment by Zevac-ZSF** [comment]
wow, I did not know that, thank you !!!
