### ISSUE TITLE
placing one powder snow from stacked powder snow buckets, consumes all buckets

### ISSUE THREAD

**Issue by Zevac-ZSF** [bakrun/stackitem64#7]
Hello again,

I'm happily using your mod :-)

But I found that when I have a 16-stack of Powder Snow bucket and place one Powder Snow, I am left with 1 empty bucket, the other 15 disappeared ;-(

I tested it with Water buckets and Lava buckets, but they work fine.

Can you fix that?

Thank you in advance

Z.

**Comment by bakrun** [comment]
yes fix that
